In [2]:
import tensorflow as tf
print(tf.__version__)

2.19.0


In [18]:
import tensorflow as tf   # Import TensorFlow library

print("\n" + "="*60)
print("         TENSOR CREATION EXPERIMENT         ")
print("="*60)

# Creating a Scalar Tensor (Single Value)
scalar = tf.constant(10)

# Creating a Vector Tensor (1-D Array)
vector = tf.constant([1, 2, 3, 4])

# Creating a 2-D Matrix Tensor (Rows & Columns)
matrix2d = tf.constant([
    [1, 2],
    [3, 4]
])

# Creating a 3-D Matrix Tensor (Stack of 2-D Matrices)
matrix3d = tf.constant([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

# Displaying Scalar Tensor
print("\n Scalar Tensor (Single Value)")
print(scalar)

# Displaying Vector Tensor
print("\n Vector Tensor (1-D Tensor)")
print(vector)

# Displaying 2D Matrix Tensor
print("\n 2D Matrix Tensor")
print(matrix2d)

# Displaying 3D Matrix Tensor
print("\n 3D Matrix Tensor")
print(matrix3d)

print("\n✔ All Tensors Created and Displayed Successfully")
print("="*60)


         TENSOR CREATION EXPERIMENT         

 Scalar Tensor (Single Value)
tf.Tensor(10, shape=(), dtype=int32)

 Vector Tensor (1-D Tensor)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)

 2D Matrix Tensor
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)

 3D Matrix Tensor
tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)

✔ All Tensors Created and Displayed Successfully


In [17]:
# Experiment 3
# Basic Tensor Operations on Scalar, Vector and Matrix
# This program demonstrates addition, subtraction,
# multiplication and division using TensorFlow

import tensorflow as tf

print("=" * 70)
print("        EXPERIMENT 3: TENSOR OPERATIONS (SCALAR, VECTOR, MATRIX)")
print("=" * 70)

# -------------------- SCALAR OPERATIONS --------------------
print("\n SCALAR TENSOR OPERATIONS")
print("-" * 70)

# Creating scalar tensors
scalar_a = tf.constant(20, dtype=tf.float32)
scalar_b = tf.constant(10, dtype=tf.float32)

# Printing scalar tensors
print(f"Scalar A : {scalar_a.numpy()}")
print(f"Scalar B : {scalar_b.numpy()}")

# Performing operations on scalars
print("\nResults:")
print(f"Addition        (A + B) : {(scalar_a + scalar_b).numpy()}")
print(f"Subtraction     (A - B) : {(scalar_a - scalar_b).numpy()}")
print(f"Multiplication (A * B) : {(scalar_a * scalar_b).numpy()}")
print(f"Division        (A / B) : {(scalar_a / scalar_b).numpy()}")

# -------------------- VECTOR OPERATIONS --------------------
print("\n VECTOR TENSOR OPERATIONS")
print("-" * 70)

# Creating vector tensors
vector_a = tf.constant([10, 20, 30], dtype=tf.float32)
vector_b = tf.constant([5, 10, 15], dtype=tf.float32)

# Printing vector tensors
print("Vector A :", vector_a.numpy())
print("Vector B :", vector_b.numpy())

# Performing operations on vectors
print("\nResults:")
print("Addition        (A + B) :", (vector_a + vector_b).numpy())
print("Subtraction     (A - B) :", (vector_a - vector_b).numpy())
print("Multiplication (A * B) :", (vector_a * vector_b).numpy())
print("Division        (A / B) :", (vector_a / vector_b).numpy())

# -------------------- MATRIX OPERATIONS --------------------
print("\n MATRIX TENSOR OPERATIONS")
print("-" * 70)

# Creating matrix tensors
matrix_a = tf.constant([[1, 2, 3],
                         [4, 5, 6]], dtype=tf.float32)

matrix_b = tf.constant([[1, 1, 1],
                         [2, 2, 2]], dtype=tf.float32)

# Printing matrix tensors
print("Matrix A:\n", matrix_a.numpy())
print("Matrix B:\n", matrix_b.numpy())

# Performing operations on matrices
print("\nResults:")
print("Addition (A + B):\n", (matrix_a + matrix_b).numpy())
print("Subtraction (A - B):\n", (matrix_a - matrix_b).numpy())
print("Multiplication (A * B):\n", (matrix_a * matrix_b).numpy())
print("Division (A / B):\n", (matrix_a / matrix_b).numpy())

print("\n" + "=" * 70)
print("     ALL SCALAR, VECTOR & MATRIX OPERATIONS EXECUTED SUCCESSFULLY")
print("=" * 70)


        EXPERIMENT 3: TENSOR OPERATIONS (SCALAR, VECTOR, MATRIX)

 SCALAR TENSOR OPERATIONS
----------------------------------------------------------------------
Scalar A : 20.0
Scalar B : 10.0

Results:
Addition        (A + B) : 30.0
Subtraction     (A - B) : 10.0
Multiplication (A * B) : 200.0
Division        (A / B) : 2.0

 VECTOR TENSOR OPERATIONS
----------------------------------------------------------------------
Vector A : [10. 20. 30.]
Vector B : [ 5. 10. 15.]

Results:
Addition        (A + B) : [15. 30. 45.]
Subtraction     (A - B) : [ 5. 10. 15.]
Multiplication (A * B) : [ 50. 200. 450.]
Division        (A / B) : [2. 2. 2.]

 MATRIX TENSOR OPERATIONS
----------------------------------------------------------------------
Matrix A:
 [[1. 2. 3.]
 [4. 5. 6.]]
Matrix B:
 [[1. 1. 1.]
 [2. 2. 2.]]

Results:
Addition (A + B):
 [[2. 3. 4.]
 [6. 7. 8.]]
Subtraction (A - B):
 [[0. 1. 2.]
 [2. 3. 4.]]
Multiplication (A * B):
 [[ 1.  2.  3.]
 [ 8. 10. 12.]]
Division (A / B):
 [[1.  2. 

In [12]:
# Experiment 4
# Exploring Tensor Properties: Data Type, Shape and Dimensions
# This program demonstrates tensor properties for
# Scalar, Vector and Matrix using TensorFlow

import tensorflow as tf

print("=" * 75)
print("        EXPERIMENT 4: TENSOR PROPERTIES ANALYSIS")
print("        (SCALAR, VECTOR & MATRIX)")
print("=" * 75)

# ==================== SCALAR TENSOR ====================
print("\n SCALAR TENSOR PROPERTIES")
print("-" * 75)

# Creating a scalar tensor
scalar = tf.constant(25, dtype=tf.int32)

# Displaying scalar tensor
print("Scalar Tensor Value :", scalar.numpy())

# Displaying scalar properties
print("\nProperties:")
print("Data Type          :", scalar.dtype)
print("Shape              :", scalar.shape)
print("Dimensions (ndim)  :", scalar.ndim)

# ==================== VECTOR TENSOR ====================
print("\n VECTOR TENSOR PROPERTIES")
print("-" * 75)

# Creating a vector tensor
vector = tf.constant([10, 20, 30, 40], dtype=tf.float32)

# Displaying vector tensor
print("Vector Tensor Value :", vector.numpy())

# Displaying vector properties
print("\nProperties:")
print("Data Type           :", vector.dtype)
print("Shape               :", vector.shape)
print("Dimensions (ndim)   :", vector.ndim)

# ==================== MATRIX TENSOR ====================
print("\n MATRIX TENSOR PROPERTIES")
print("-" * 75)

# Creating a matrix tensor
matrix = tf.constant([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]], dtype=tf.float64)

# Displaying matrix tensor
print("Matrix Tensor Value:")
print(matrix.numpy())

# Displaying matrix properties
print("\nProperties:")
print("Data Type           :", matrix.dtype)
print("Shape               :", matrix.shape)
print("Dimensions (ndim)   :", matrix.ndim)

print("\n" + "=" * 75)
print("     TENSOR PROPERTY ANALYSIS COMPLETED SUCCESSFULLY")
print("=" * 75)


        EXPERIMENT 4: TENSOR PROPERTIES ANALYSIS
        (SCALAR, VECTOR & MATRIX)

 SCALAR TENSOR PROPERTIES
---------------------------------------------------------------------------
Scalar Tensor Value : 25

Properties:
Data Type          : <dtype: 'int32'>
Shape              : ()
Dimensions (ndim)  : 0

 VECTOR TENSOR PROPERTIES
---------------------------------------------------------------------------
Vector Tensor Value : [10. 20. 30. 40.]

Properties:
Data Type           : <dtype: 'float32'>
Shape               : (4,)
Dimensions (ndim)   : 1

 MATRIX TENSOR PROPERTIES
---------------------------------------------------------------------------
Matrix Tensor Value:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

Properties:
Data Type           : <dtype: 'float64'>
Shape               : (3, 3)
Dimensions (ndim)   : 2

     TENSOR PROPERTY ANALYSIS COMPLETED SUCCESSFULLY


In [14]:
# Experiment 5
# This program converts a NumPy array into a TensorFlow tensor
# and displays both along with their data types

import tensorflow as tf
import numpy as np

print("\n===== EXPERIMENT 5: NUMPY TO TENSORFLOW CONVERSION =====\n")

# Creating a NumPy array
numpy_array = np.array([10, 20, 30, 40, 50])

print("NumPy Array")
print("Value      :", numpy_array)
print("Data Type  :", numpy_array.dtype)

print("\n-----------------------------------------------\n")

# Converting NumPy array to TensorFlow tensor
tf_tensor = tf.convert_to_tensor(numpy_array)

print("TensorFlow Tensor")
print("Value      :", tf_tensor.numpy())
print("Data Type  :", tf_tensor.dtype)
print("Shape      :", tf_tensor.shape)
print("Dimensions :", tf_tensor.ndim)

print("\n===== Experiment 5 Completed Successfully =====\n")



===== EXPERIMENT 5: NUMPY TO TENSORFLOW CONVERSION =====

NumPy Array
Value      : [10 20 30 40 50]
Data Type  : int64

-----------------------------------------------

TensorFlow Tensor
Value      : [10 20 30 40 50]
Data Type  : <dtype: 'int64'>
Shape      : (5,)
Dimensions : 1

===== Experiment 5 Completed Successfully =====

